spring:
  application:
    name: kiwoom-prod
  config:
    import:
      - classpath:config/fsb/env-prod.properties
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    jdbc-url: jdbc:oracle:thin:@192.168.0.105:1521/orcl
    username: FORESYS
    password: ENC(hyihyMmq0uweGyc2ULz0jqDRXVD9cmYP)
  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    database: oracle
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        jdbc.lob.non_contextual_creation: true

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  config-location: classpath:config/mybatis/mybatis-config.xml
  type-aliases-package: com.kiwoom.**.model

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"

springdoc:
  swagger-ui:
    path: /

jasypt:
  encryptor:
    password: foresys**
    algorithm: PBEWithMD5AndDES
    key-obtention-iterations: 1000
    pool-size: 1
    provider-name: SunJCE
    salt-generator-classname: org.jasypt.salt.RandomSaltGenerator
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
    string-output-type: base64
    bean: jasyptStringEncryptor

juso:
  base-url: https://business.juso.go.kr
  apiKey: devU01TX0FVVEgyMDI1MDMzMTE0NTYyMzExNTU5Mzk=