spring:
  application:
    name: app1
  config:
    import:
      - classpath:core-local.yml
      - classpath:config/mybatis/mybatis.yml
      - classpath:config/db/database-local.yml
      - classpath:config/logback/logback-local.yml
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: app1
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
      enable-auto-commit: true
server:
  port: 10010
springdoc:
  swagger-ui:
    path: /
