spring:
  application:
    name: sequence
  data:
    redis:
      host: localhost
      port: 6379
      connect-timeout: 1000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 4